// flow-typed signature: aac39034672af305ae689ad8d588d9b5
// flow-typed version: <<STUB>>/bell_v^8.5.0/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bell'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'bell' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'bell/lib/index' {
  declare module.exports: any;
}

declare module 'bell/lib/oauth' {
  declare module.exports: any;
}

declare module 'bell/lib/providers/arcgisonline' {
  declare module.exports: any;
}

declare module 'bell/lib/providers/auth0' {
  declare module.exports: any;
}

declare module 'bell/lib/providers/azuread' {
  declare module.exports: any;
}

declare module 'bell/lib/providers/bitbucket' {
  declare module.exports: any;
}

declare module 'bell/lib/providers/discord' {
  declare module.exports: any;
}

declare module 'bell/lib/providers/dropbox' {
  declare module.exports: any;
}

declare module 'bell/lib/providers/facebook' {
  declare module.exports: any;
}

declare module 'bell/lib/providers/fitbit' {
  declare module.exports: any;
}

declare module 'bell/lib/providers/foursquare' {
  declare module.exports: any;
}

declare module 'bell/lib/providers/github' {
  declare module.exports: any;
}

declare module 'bell/lib/providers/gitlab' {
  declare module.exports: any;
}

declare module 'bell/lib/providers/google' {
  declare module.exports: any;
}

declare module 'bell/lib/providers/googleplus' {
  declare module.exports: any;
}

declare module 'bell/lib/providers/index' {
  declare module.exports: any;
}

declare module 'bell/lib/providers/instagram' {
  declare module.exports: any;
}

declare module 'bell/lib/providers/linkedin' {
  declare module.exports: any;
}

declare module 'bell/lib/providers/live' {
  declare module.exports: any;
}

declare module 'bell/lib/providers/medium' {
  declare module.exports: any;
}

declare module 'bell/lib/providers/meetup' {
  declare module.exports: any;
}

declare module 'bell/lib/providers/nest' {
  declare module.exports: any;
}

declare module 'bell/lib/providers/office365' {
  declare module.exports: any;
}

declare module 'bell/lib/providers/okta' {
  declare module.exports: any;
}

declare module 'bell/lib/providers/phabricator' {
  declare module.exports: any;
}

declare module 'bell/lib/providers/pingfed' {
  declare module.exports: any;
}

declare module 'bell/lib/providers/pinterest' {
  declare module.exports: any;
}

declare module 'bell/lib/providers/reddit' {
  declare module.exports: any;
}

declare module 'bell/lib/providers/salesforce' {
  declare module.exports: any;
}

declare module 'bell/lib/providers/slack' {
  declare module.exports: any;
}

declare module 'bell/lib/providers/spotify' {
  declare module.exports: any;
}

declare module 'bell/lib/providers/tumblr' {
  declare module.exports: any;
}

declare module 'bell/lib/providers/twitch' {
  declare module.exports: any;
}

declare module 'bell/lib/providers/twitter' {
  declare module.exports: any;
}

declare module 'bell/lib/providers/vk' {
  declare module.exports: any;
}

declare module 'bell/lib/providers/wordpress' {
  declare module.exports: any;
}

declare module 'bell/lib/providers/yahoo' {
  declare module.exports: any;
}

// Filename aliases
declare module 'bell/lib/index.js' {
  declare module.exports: $Exports<'bell/lib/index'>;
}
declare module 'bell/lib/oauth.js' {
  declare module.exports: $Exports<'bell/lib/oauth'>;
}
declare module 'bell/lib/providers/arcgisonline.js' {
  declare module.exports: $Exports<'bell/lib/providers/arcgisonline'>;
}
declare module 'bell/lib/providers/auth0.js' {
  declare module.exports: $Exports<'bell/lib/providers/auth0'>;
}
declare module 'bell/lib/providers/azuread.js' {
  declare module.exports: $Exports<'bell/lib/providers/azuread'>;
}
declare module 'bell/lib/providers/bitbucket.js' {
  declare module.exports: $Exports<'bell/lib/providers/bitbucket'>;
}
declare module 'bell/lib/providers/discord.js' {
  declare module.exports: $Exports<'bell/lib/providers/discord'>;
}
declare module 'bell/lib/providers/dropbox.js' {
  declare module.exports: $Exports<'bell/lib/providers/dropbox'>;
}
declare module 'bell/lib/providers/facebook.js' {
  declare module.exports: $Exports<'bell/lib/providers/facebook'>;
}
declare module 'bell/lib/providers/fitbit.js' {
  declare module.exports: $Exports<'bell/lib/providers/fitbit'>;
}
declare module 'bell/lib/providers/foursquare.js' {
  declare module.exports: $Exports<'bell/lib/providers/foursquare'>;
}
declare module 'bell/lib/providers/github.js' {
  declare module.exports: $Exports<'bell/lib/providers/github'>;
}
declare module 'bell/lib/providers/gitlab.js' {
  declare module.exports: $Exports<'bell/lib/providers/gitlab'>;
}
declare module 'bell/lib/providers/google.js' {
  declare module.exports: $Exports<'bell/lib/providers/google'>;
}
declare module 'bell/lib/providers/googleplus.js' {
  declare module.exports: $Exports<'bell/lib/providers/googleplus'>;
}
declare module 'bell/lib/providers/index.js' {
  declare module.exports: $Exports<'bell/lib/providers/index'>;
}
declare module 'bell/lib/providers/instagram.js' {
  declare module.exports: $Exports<'bell/lib/providers/instagram'>;
}
declare module 'bell/lib/providers/linkedin.js' {
  declare module.exports: $Exports<'bell/lib/providers/linkedin'>;
}
declare module 'bell/lib/providers/live.js' {
  declare module.exports: $Exports<'bell/lib/providers/live'>;
}
declare module 'bell/lib/providers/medium.js' {
  declare module.exports: $Exports<'bell/lib/providers/medium'>;
}
declare module 'bell/lib/providers/meetup.js' {
  declare module.exports: $Exports<'bell/lib/providers/meetup'>;
}
declare module 'bell/lib/providers/nest.js' {
  declare module.exports: $Exports<'bell/lib/providers/nest'>;
}
declare module 'bell/lib/providers/office365.js' {
  declare module.exports: $Exports<'bell/lib/providers/office365'>;
}
declare module 'bell/lib/providers/okta.js' {
  declare module.exports: $Exports<'bell/lib/providers/okta'>;
}
declare module 'bell/lib/providers/phabricator.js' {
  declare module.exports: $Exports<'bell/lib/providers/phabricator'>;
}
declare module 'bell/lib/providers/pingfed.js' {
  declare module.exports: $Exports<'bell/lib/providers/pingfed'>;
}
declare module 'bell/lib/providers/pinterest.js' {
  declare module.exports: $Exports<'bell/lib/providers/pinterest'>;
}
declare module 'bell/lib/providers/reddit.js' {
  declare module.exports: $Exports<'bell/lib/providers/reddit'>;
}
declare module 'bell/lib/providers/salesforce.js' {
  declare module.exports: $Exports<'bell/lib/providers/salesforce'>;
}
declare module 'bell/lib/providers/slack.js' {
  declare module.exports: $Exports<'bell/lib/providers/slack'>;
}
declare module 'bell/lib/providers/spotify.js' {
  declare module.exports: $Exports<'bell/lib/providers/spotify'>;
}
declare module 'bell/lib/providers/tumblr.js' {
  declare module.exports: $Exports<'bell/lib/providers/tumblr'>;
}
declare module 'bell/lib/providers/twitch.js' {
  declare module.exports: $Exports<'bell/lib/providers/twitch'>;
}
declare module 'bell/lib/providers/twitter.js' {
  declare module.exports: $Exports<'bell/lib/providers/twitter'>;
}
declare module 'bell/lib/providers/vk.js' {
  declare module.exports: $Exports<'bell/lib/providers/vk'>;
}
declare module 'bell/lib/providers/wordpress.js' {
  declare module.exports: $Exports<'bell/lib/providers/wordpress'>;
}
declare module 'bell/lib/providers/yahoo.js' {
  declare module.exports: $Exports<'bell/lib/providers/yahoo'>;
}
