// flow-typed signature: 66d468ce927f556ec0ffba0cb7d8741f
// flow-typed version: <<STUB>>/glue_v^4.1.0/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'glue'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'glue' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'glue/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'glue/lib/index.js' {
  declare module.exports: $Exports<'glue/lib/index'>;
}
