// flow-typed signature: ac2448c254bbd8906eb3e369e14acbdd
// flow-typed version: <<STUB>>/h2o2_v^5.4.0/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'h2o2'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'h2o2' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'h2o2/lib/index' {
  declare module.exports: any;
}

declare module 'h2o2/test/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'h2o2/lib/index.js' {
  declare module.exports: $Exports<'h2o2/lib/index'>;
}
declare module 'h2o2/test/index.js' {
  declare module.exports: $Exports<'h2o2/test/index'>;
}
