// flow-typed signature: ea5f36e8ba07faa14438acedd1ca7827
// flow-typed version: <<STUB>>/hapi-mongodb_v^6.2.1/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'hapi-mongodb'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'hapi-mongodb' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'hapi-mongodb/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'hapi-mongodb/lib/index.js' {
  declare module.exports: $Exports<'hapi-mongodb/lib/index'>;
}
