// flow-typed signature: 35d4adf390975fd555fc8e91ca4dae5d
// flow-typed version: <<STUB>>/hapi-swagger_v^7.7.0/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'hapi-swagger'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'hapi-swagger' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'hapi-swagger/examples/assets/extendedjoi' {
  declare module.exports: any;
}

declare module 'hapi-swagger/examples/assets/routes-complex' {
  declare module.exports: any;
}

declare module 'hapi-swagger/examples/assets/routes-simple' {
  declare module.exports: any;
}

declare module 'hapi-swagger/examples/basic' {
  declare module.exports: any;
}

declare module 'hapi-swagger/examples/connections-sep-docs' {
  declare module.exports: any;
}

declare module 'hapi-swagger/examples/connections' {
  declare module.exports: any;
}

declare module 'hapi-swagger/examples/custom' {
  declare module.exports: any;
}

declare module 'hapi-swagger/examples/debug' {
  declare module.exports: any;
}

declare module 'hapi-swagger/examples/dot-grouping' {
  declare module.exports: any;
}

declare module 'hapi-swagger/examples/extend' {
  declare module.exports: any;
}

declare module 'hapi-swagger/examples/group-ordered' {
  declare module.exports: any;
}

declare module 'hapi-swagger/examples/jwt' {
  declare module.exports: any;
}

declare module 'hapi-swagger/examples/options' {
  declare module.exports: any;
}

declare module 'hapi-swagger/examples/promise' {
  declare module.exports: any;
}

declare module 'hapi-swagger/examples/ssl' {
  declare module.exports: any;
}

declare module 'hapi-swagger/examples/swagger-client' {
  declare module.exports: any;
}

declare module 'hapi-swagger/examples/upload-file' {
  declare module.exports: any;
}

declare module 'hapi-swagger/examples/versions' {
  declare module.exports: any;
}

declare module 'hapi-swagger/lib/builder' {
  declare module.exports: any;
}

declare module 'hapi-swagger/lib/defaults' {
  declare module.exports: any;
}

declare module 'hapi-swagger/lib/definitions' {
  declare module.exports: any;
}

declare module 'hapi-swagger/lib/filter' {
  declare module.exports: any;
}

declare module 'hapi-swagger/lib/group' {
  declare module.exports: any;
}

declare module 'hapi-swagger/lib/hash' {
  declare module.exports: any;
}

declare module 'hapi-swagger/lib/index' {
  declare module.exports: any;
}

declare module 'hapi-swagger/lib/info' {
  declare module.exports: any;
}

declare module 'hapi-swagger/lib/parameters' {
  declare module.exports: any;
}

declare module 'hapi-swagger/lib/paths' {
  declare module.exports: any;
}

declare module 'hapi-swagger/lib/properties' {
  declare module.exports: any;
}

declare module 'hapi-swagger/lib/responses' {
  declare module.exports: any;
}

declare module 'hapi-swagger/lib/sort' {
  declare module.exports: any;
}

declare module 'hapi-swagger/lib/tags' {
  declare module.exports: any;
}

declare module 'hapi-swagger/lib/utilities' {
  declare module.exports: any;
}

declare module 'hapi-swagger/lib/validate' {
  declare module.exports: any;
}

declare module 'hapi-swagger/public/extend' {
  declare module.exports: any;
}

declare module 'hapi-swagger/public/swaggerui/lang/en' {
  declare module.exports: any;
}

declare module 'hapi-swagger/public/swaggerui/lang/es' {
  declare module.exports: any;
}

declare module 'hapi-swagger/public/swaggerui/lang/fr' {
  declare module.exports: any;
}

declare module 'hapi-swagger/public/swaggerui/lang/it' {
  declare module.exports: any;
}

declare module 'hapi-swagger/public/swaggerui/lang/ja' {
  declare module.exports: any;
}

declare module 'hapi-swagger/public/swaggerui/lang/pl' {
  declare module.exports: any;
}

declare module 'hapi-swagger/public/swaggerui/lang/pt' {
  declare module.exports: any;
}

declare module 'hapi-swagger/public/swaggerui/lang/ru' {
  declare module.exports: any;
}

declare module 'hapi-swagger/public/swaggerui/lang/tr' {
  declare module.exports: any;
}

declare module 'hapi-swagger/public/swaggerui/lang/translator' {
  declare module.exports: any;
}

declare module 'hapi-swagger/public/swaggerui/lang/zh-cn' {
  declare module.exports: any;
}

declare module 'hapi-swagger/public/swaggerui/lib/backbone-min' {
  declare module.exports: any;
}

declare module 'hapi-swagger/public/swaggerui/lib/handlebars-2.0.0' {
  declare module.exports: any;
}

declare module 'hapi-swagger/public/swaggerui/lib/highlight.7.3.pack' {
  declare module.exports: any;
}

declare module 'hapi-swagger/public/swaggerui/lib/jquery-1.8.0.min' {
  declare module.exports: any;
}

declare module 'hapi-swagger/public/swaggerui/lib/jquery.ba-bbq.min' {
  declare module.exports: any;
}

declare module 'hapi-swagger/public/swaggerui/lib/jquery.slideto.min' {
  declare module.exports: any;
}

declare module 'hapi-swagger/public/swaggerui/lib/jquery.wiggle.min' {
  declare module.exports: any;
}

declare module 'hapi-swagger/public/swaggerui/lib/js-yaml.min' {
  declare module.exports: any;
}

declare module 'hapi-swagger/public/swaggerui/lib/jsoneditor.min' {
  declare module.exports: any;
}

declare module 'hapi-swagger/public/swaggerui/lib/lodash.min' {
  declare module.exports: any;
}

declare module 'hapi-swagger/public/swaggerui/lib/marked' {
  declare module.exports: any;
}

declare module 'hapi-swagger/public/swaggerui/lib/swagger-oauth' {
  declare module.exports: any;
}

declare module 'hapi-swagger/public/swaggerui/swagger-ui' {
  declare module.exports: any;
}

declare module 'hapi-swagger/public/swaggerui/swagger-ui.min' {
  declare module.exports: any;
}

declare module 'hapi-swagger/test/helper' {
  declare module.exports: any;
}

declare module 'hapi-swagger/test/integration/alternatives-test' {
  declare module.exports: any;
}

declare module 'hapi-swagger/test/integration/authentication-test' {
  declare module.exports: any;
}

declare module 'hapi-swagger/test/integration/builder-test' {
  declare module.exports: any;
}

declare module 'hapi-swagger/test/integration/cache-test' {
  declare module.exports: any;
}

declare module 'hapi-swagger/test/integration/child-model' {
  declare module.exports: any;
}

declare module 'hapi-swagger/test/integration/connections-test' {
  declare module.exports: any;
}

declare module 'hapi-swagger/test/integration/debug-test' {
  declare module.exports: any;
}

declare module 'hapi-swagger/test/integration/definitions-test' {
  declare module.exports: any;
}

declare module 'hapi-swagger/test/integration/dereference-test' {
  declare module.exports: any;
}

declare module 'hapi-swagger/test/integration/document-other-connection-test' {
  declare module.exports: any;
}

declare module 'hapi-swagger/test/integration/file-test' {
  declare module.exports: any;
}

declare module 'hapi-swagger/test/integration/filter-test' {
  declare module.exports: any;
}

declare module 'hapi-swagger/test/integration/grouping-test' {
  declare module.exports: any;
}

declare module 'hapi-swagger/test/integration/info-test' {
  declare module.exports: any;
}

declare module 'hapi-swagger/test/integration/joifunctions-test' {
  declare module.exports: any;
}

declare module 'hapi-swagger/test/integration/lout-test' {
  declare module.exports: any;
}

declare module 'hapi-swagger/test/integration/path-test' {
  declare module.exports: any;
}

declare module 'hapi-swagger/test/integration/plugin-test' {
  declare module.exports: any;
}

declare module 'hapi-swagger/test/integration/proxy-test' {
  declare module.exports: any;
}

declare module 'hapi-swagger/test/integration/responses-tests' {
  declare module.exports: any;
}

declare module 'hapi-swagger/test/integration/security-test' {
  declare module.exports: any;
}

declare module 'hapi-swagger/test/integration/sorted-test' {
  declare module.exports: any;
}

declare module 'hapi-swagger/test/integration/tags-test' {
  declare module.exports: any;
}

declare module 'hapi-swagger/test/integration/wildcard-routes' {
  declare module.exports: any;
}

declare module 'hapi-swagger/test/unit/group-test' {
  declare module.exports: any;
}

declare module 'hapi-swagger/test/unit/property-test' {
  declare module.exports: any;
}

declare module 'hapi-swagger/test/unit/utilities-test' {
  declare module.exports: any;
}

declare module 'hapi-swagger/test/unit/validate-test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'hapi-swagger/examples/assets/extendedjoi.js' {
  declare module.exports: $Exports<'hapi-swagger/examples/assets/extendedjoi'>;
}
declare module 'hapi-swagger/examples/assets/routes-complex.js' {
  declare module.exports: $Exports<'hapi-swagger/examples/assets/routes-complex'>;
}
declare module 'hapi-swagger/examples/assets/routes-simple.js' {
  declare module.exports: $Exports<'hapi-swagger/examples/assets/routes-simple'>;
}
declare module 'hapi-swagger/examples/basic.js' {
  declare module.exports: $Exports<'hapi-swagger/examples/basic'>;
}
declare module 'hapi-swagger/examples/connections-sep-docs.js' {
  declare module.exports: $Exports<'hapi-swagger/examples/connections-sep-docs'>;
}
declare module 'hapi-swagger/examples/connections.js' {
  declare module.exports: $Exports<'hapi-swagger/examples/connections'>;
}
declare module 'hapi-swagger/examples/custom.js' {
  declare module.exports: $Exports<'hapi-swagger/examples/custom'>;
}
declare module 'hapi-swagger/examples/debug.js' {
  declare module.exports: $Exports<'hapi-swagger/examples/debug'>;
}
declare module 'hapi-swagger/examples/dot-grouping.js' {
  declare module.exports: $Exports<'hapi-swagger/examples/dot-grouping'>;
}
declare module 'hapi-swagger/examples/extend.js' {
  declare module.exports: $Exports<'hapi-swagger/examples/extend'>;
}
declare module 'hapi-swagger/examples/group-ordered.js' {
  declare module.exports: $Exports<'hapi-swagger/examples/group-ordered'>;
}
declare module 'hapi-swagger/examples/jwt.js' {
  declare module.exports: $Exports<'hapi-swagger/examples/jwt'>;
}
declare module 'hapi-swagger/examples/options.js' {
  declare module.exports: $Exports<'hapi-swagger/examples/options'>;
}
declare module 'hapi-swagger/examples/promise.js' {
  declare module.exports: $Exports<'hapi-swagger/examples/promise'>;
}
declare module 'hapi-swagger/examples/ssl.js' {
  declare module.exports: $Exports<'hapi-swagger/examples/ssl'>;
}
declare module 'hapi-swagger/examples/swagger-client.js' {
  declare module.exports: $Exports<'hapi-swagger/examples/swagger-client'>;
}
declare module 'hapi-swagger/examples/upload-file.js' {
  declare module.exports: $Exports<'hapi-swagger/examples/upload-file'>;
}
declare module 'hapi-swagger/examples/versions.js' {
  declare module.exports: $Exports<'hapi-swagger/examples/versions'>;
}
declare module 'hapi-swagger/index' {
  declare module.exports: $Exports<'hapi-swagger'>;
}
declare module 'hapi-swagger/index.js' {
  declare module.exports: $Exports<'hapi-swagger'>;
}
declare module 'hapi-swagger/lib/builder.js' {
  declare module.exports: $Exports<'hapi-swagger/lib/builder'>;
}
declare module 'hapi-swagger/lib/defaults.js' {
  declare module.exports: $Exports<'hapi-swagger/lib/defaults'>;
}
declare module 'hapi-swagger/lib/definitions.js' {
  declare module.exports: $Exports<'hapi-swagger/lib/definitions'>;
}
declare module 'hapi-swagger/lib/filter.js' {
  declare module.exports: $Exports<'hapi-swagger/lib/filter'>;
}
declare module 'hapi-swagger/lib/group.js' {
  declare module.exports: $Exports<'hapi-swagger/lib/group'>;
}
declare module 'hapi-swagger/lib/hash.js' {
  declare module.exports: $Exports<'hapi-swagger/lib/hash'>;
}
declare module 'hapi-swagger/lib/index.js' {
  declare module.exports: $Exports<'hapi-swagger/lib/index'>;
}
declare module 'hapi-swagger/lib/info.js' {
  declare module.exports: $Exports<'hapi-swagger/lib/info'>;
}
declare module 'hapi-swagger/lib/parameters.js' {
  declare module.exports: $Exports<'hapi-swagger/lib/parameters'>;
}
declare module 'hapi-swagger/lib/paths.js' {
  declare module.exports: $Exports<'hapi-swagger/lib/paths'>;
}
declare module 'hapi-swagger/lib/properties.js' {
  declare module.exports: $Exports<'hapi-swagger/lib/properties'>;
}
declare module 'hapi-swagger/lib/responses.js' {
  declare module.exports: $Exports<'hapi-swagger/lib/responses'>;
}
declare module 'hapi-swagger/lib/sort.js' {
  declare module.exports: $Exports<'hapi-swagger/lib/sort'>;
}
declare module 'hapi-swagger/lib/tags.js' {
  declare module.exports: $Exports<'hapi-swagger/lib/tags'>;
}
declare module 'hapi-swagger/lib/utilities.js' {
  declare module.exports: $Exports<'hapi-swagger/lib/utilities'>;
}
declare module 'hapi-swagger/lib/validate.js' {
  declare module.exports: $Exports<'hapi-swagger/lib/validate'>;
}
declare module 'hapi-swagger/public/extend.js' {
  declare module.exports: $Exports<'hapi-swagger/public/extend'>;
}
declare module 'hapi-swagger/public/swaggerui/lang/en.js' {
  declare module.exports: $Exports<'hapi-swagger/public/swaggerui/lang/en'>;
}
declare module 'hapi-swagger/public/swaggerui/lang/es.js' {
  declare module.exports: $Exports<'hapi-swagger/public/swaggerui/lang/es'>;
}
declare module 'hapi-swagger/public/swaggerui/lang/fr.js' {
  declare module.exports: $Exports<'hapi-swagger/public/swaggerui/lang/fr'>;
}
declare module 'hapi-swagger/public/swaggerui/lang/it.js' {
  declare module.exports: $Exports<'hapi-swagger/public/swaggerui/lang/it'>;
}
declare module 'hapi-swagger/public/swaggerui/lang/ja.js' {
  declare module.exports: $Exports<'hapi-swagger/public/swaggerui/lang/ja'>;
}
declare module 'hapi-swagger/public/swaggerui/lang/pl.js' {
  declare module.exports: $Exports<'hapi-swagger/public/swaggerui/lang/pl'>;
}
declare module 'hapi-swagger/public/swaggerui/lang/pt.js' {
  declare module.exports: $Exports<'hapi-swagger/public/swaggerui/lang/pt'>;
}
declare module 'hapi-swagger/public/swaggerui/lang/ru.js' {
  declare module.exports: $Exports<'hapi-swagger/public/swaggerui/lang/ru'>;
}
declare module 'hapi-swagger/public/swaggerui/lang/tr.js' {
  declare module.exports: $Exports<'hapi-swagger/public/swaggerui/lang/tr'>;
}
declare module 'hapi-swagger/public/swaggerui/lang/translator.js' {
  declare module.exports: $Exports<'hapi-swagger/public/swaggerui/lang/translator'>;
}
declare module 'hapi-swagger/public/swaggerui/lang/zh-cn.js' {
  declare module.exports: $Exports<'hapi-swagger/public/swaggerui/lang/zh-cn'>;
}
declare module 'hapi-swagger/public/swaggerui/lib/backbone-min.js' {
  declare module.exports: $Exports<'hapi-swagger/public/swaggerui/lib/backbone-min'>;
}
declare module 'hapi-swagger/public/swaggerui/lib/handlebars-2.0.0.js' {
  declare module.exports: $Exports<'hapi-swagger/public/swaggerui/lib/handlebars-2.0.0'>;
}
declare module 'hapi-swagger/public/swaggerui/lib/highlight.7.3.pack.js' {
  declare module.exports: $Exports<'hapi-swagger/public/swaggerui/lib/highlight.7.3.pack'>;
}
declare module 'hapi-swagger/public/swaggerui/lib/jquery-1.8.0.min.js' {
  declare module.exports: $Exports<'hapi-swagger/public/swaggerui/lib/jquery-1.8.0.min'>;
}
declare module 'hapi-swagger/public/swaggerui/lib/jquery.ba-bbq.min.js' {
  declare module.exports: $Exports<'hapi-swagger/public/swaggerui/lib/jquery.ba-bbq.min'>;
}
declare module 'hapi-swagger/public/swaggerui/lib/jquery.slideto.min.js' {
  declare module.exports: $Exports<'hapi-swagger/public/swaggerui/lib/jquery.slideto.min'>;
}
declare module 'hapi-swagger/public/swaggerui/lib/jquery.wiggle.min.js' {
  declare module.exports: $Exports<'hapi-swagger/public/swaggerui/lib/jquery.wiggle.min'>;
}
declare module 'hapi-swagger/public/swaggerui/lib/js-yaml.min.js' {
  declare module.exports: $Exports<'hapi-swagger/public/swaggerui/lib/js-yaml.min'>;
}
declare module 'hapi-swagger/public/swaggerui/lib/jsoneditor.min.js' {
  declare module.exports: $Exports<'hapi-swagger/public/swaggerui/lib/jsoneditor.min'>;
}
declare module 'hapi-swagger/public/swaggerui/lib/lodash.min.js' {
  declare module.exports: $Exports<'hapi-swagger/public/swaggerui/lib/lodash.min'>;
}
declare module 'hapi-swagger/public/swaggerui/lib/marked.js' {
  declare module.exports: $Exports<'hapi-swagger/public/swaggerui/lib/marked'>;
}
declare module 'hapi-swagger/public/swaggerui/lib/swagger-oauth.js' {
  declare module.exports: $Exports<'hapi-swagger/public/swaggerui/lib/swagger-oauth'>;
}
declare module 'hapi-swagger/public/swaggerui/swagger-ui.js' {
  declare module.exports: $Exports<'hapi-swagger/public/swaggerui/swagger-ui'>;
}
declare module 'hapi-swagger/public/swaggerui/swagger-ui.min.js' {
  declare module.exports: $Exports<'hapi-swagger/public/swaggerui/swagger-ui.min'>;
}
declare module 'hapi-swagger/test/helper.js' {
  declare module.exports: $Exports<'hapi-swagger/test/helper'>;
}
declare module 'hapi-swagger/test/integration/alternatives-test.js' {
  declare module.exports: $Exports<'hapi-swagger/test/integration/alternatives-test'>;
}
declare module 'hapi-swagger/test/integration/authentication-test.js' {
  declare module.exports: $Exports<'hapi-swagger/test/integration/authentication-test'>;
}
declare module 'hapi-swagger/test/integration/builder-test.js' {
  declare module.exports: $Exports<'hapi-swagger/test/integration/builder-test'>;
}
declare module 'hapi-swagger/test/integration/cache-test.js' {
  declare module.exports: $Exports<'hapi-swagger/test/integration/cache-test'>;
}
declare module 'hapi-swagger/test/integration/child-model.js' {
  declare module.exports: $Exports<'hapi-swagger/test/integration/child-model'>;
}
declare module 'hapi-swagger/test/integration/connections-test.js' {
  declare module.exports: $Exports<'hapi-swagger/test/integration/connections-test'>;
}
declare module 'hapi-swagger/test/integration/debug-test.js' {
  declare module.exports: $Exports<'hapi-swagger/test/integration/debug-test'>;
}
declare module 'hapi-swagger/test/integration/definitions-test.js' {
  declare module.exports: $Exports<'hapi-swagger/test/integration/definitions-test'>;
}
declare module 'hapi-swagger/test/integration/dereference-test.js' {
  declare module.exports: $Exports<'hapi-swagger/test/integration/dereference-test'>;
}
declare module 'hapi-swagger/test/integration/document-other-connection-test.js' {
  declare module.exports: $Exports<'hapi-swagger/test/integration/document-other-connection-test'>;
}
declare module 'hapi-swagger/test/integration/file-test.js' {
  declare module.exports: $Exports<'hapi-swagger/test/integration/file-test'>;
}
declare module 'hapi-swagger/test/integration/filter-test.js' {
  declare module.exports: $Exports<'hapi-swagger/test/integration/filter-test'>;
}
declare module 'hapi-swagger/test/integration/grouping-test.js' {
  declare module.exports: $Exports<'hapi-swagger/test/integration/grouping-test'>;
}
declare module 'hapi-swagger/test/integration/info-test.js' {
  declare module.exports: $Exports<'hapi-swagger/test/integration/info-test'>;
}
declare module 'hapi-swagger/test/integration/joifunctions-test.js' {
  declare module.exports: $Exports<'hapi-swagger/test/integration/joifunctions-test'>;
}
declare module 'hapi-swagger/test/integration/lout-test.js' {
  declare module.exports: $Exports<'hapi-swagger/test/integration/lout-test'>;
}
declare module 'hapi-swagger/test/integration/path-test.js' {
  declare module.exports: $Exports<'hapi-swagger/test/integration/path-test'>;
}
declare module 'hapi-swagger/test/integration/plugin-test.js' {
  declare module.exports: $Exports<'hapi-swagger/test/integration/plugin-test'>;
}
declare module 'hapi-swagger/test/integration/proxy-test.js' {
  declare module.exports: $Exports<'hapi-swagger/test/integration/proxy-test'>;
}
declare module 'hapi-swagger/test/integration/responses-tests.js' {
  declare module.exports: $Exports<'hapi-swagger/test/integration/responses-tests'>;
}
declare module 'hapi-swagger/test/integration/security-test.js' {
  declare module.exports: $Exports<'hapi-swagger/test/integration/security-test'>;
}
declare module 'hapi-swagger/test/integration/sorted-test.js' {
  declare module.exports: $Exports<'hapi-swagger/test/integration/sorted-test'>;
}
declare module 'hapi-swagger/test/integration/tags-test.js' {
  declare module.exports: $Exports<'hapi-swagger/test/integration/tags-test'>;
}
declare module 'hapi-swagger/test/integration/wildcard-routes.js' {
  declare module.exports: $Exports<'hapi-swagger/test/integration/wildcard-routes'>;
}
declare module 'hapi-swagger/test/unit/group-test.js' {
  declare module.exports: $Exports<'hapi-swagger/test/unit/group-test'>;
}
declare module 'hapi-swagger/test/unit/property-test.js' {
  declare module.exports: $Exports<'hapi-swagger/test/unit/property-test'>;
}
declare module 'hapi-swagger/test/unit/utilities-test.js' {
  declare module.exports: $Exports<'hapi-swagger/test/unit/utilities-test'>;
}
declare module 'hapi-swagger/test/unit/validate-test.js' {
  declare module.exports: $Exports<'hapi-swagger/test/unit/validate-test'>;
}
