// flow-typed signature: dce8cefe1ff5053a294f303d42520340
// flow-typed version: <<STUB>>/hapi-auth-cookie_v^6.1.1/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'hapi-auth-cookie'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'hapi-auth-cookie' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'hapi-auth-cookie/example/index' {
  declare module.exports: any;
}

declare module 'hapi-auth-cookie/lib/index' {
  declare module.exports: any;
}

declare module 'hapi-auth-cookie/test/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'hapi-auth-cookie/example/index.js' {
  declare module.exports: $Exports<'hapi-auth-cookie/example/index'>;
}
declare module 'hapi-auth-cookie/lib/index.js' {
  declare module.exports: $Exports<'hapi-auth-cookie/lib/index'>;
}
declare module 'hapi-auth-cookie/test/index.js' {
  declare module.exports: $Exports<'hapi-auth-cookie/test/index'>;
}
