// flow-typed signature: 72201a539efbcaacbd495fcc76d8babd
// flow-typed version: <<STUB>>/mongodb-test-mock_v^0.1.5/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mongodb-test-mock'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mongodb-test-mock' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mongodb-test-mock/Collection' {
  declare module.exports: any;
}

declare module 'mongodb-test-mock/Cursor' {
  declare module.exports: any;
}

declare module 'mongodb-test-mock/example' {
  declare module.exports: any;
}

declare module 'mongodb-test-mock/MongoMock' {
  declare module.exports: any;
}

declare module 'mongodb-test-mock/test' {
  declare module.exports: any;
}

declare module 'mongodb-test-mock/test/collection.spec' {
  declare module.exports: any;
}

declare module 'mongodb-test-mock/test/common' {
  declare module.exports: any;
}

declare module 'mongodb-test-mock/test/jshint.spec' {
  declare module.exports: any;
}

declare module 'mongodb-test-mock/test/MongoMock.spec' {
  declare module.exports: any;
}

declare module 'mongodb-test-mock/test/util.spec' {
  declare module.exports: any;
}

declare module 'mongodb-test-mock/util/index' {
  declare module.exports: any;
}

declare module 'mongodb-test-mock/util/objectUtil' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mongodb-test-mock/Collection.js' {
  declare module.exports: $Exports<'mongodb-test-mock/Collection'>;
}
declare module 'mongodb-test-mock/Cursor.js' {
  declare module.exports: $Exports<'mongodb-test-mock/Cursor'>;
}
declare module 'mongodb-test-mock/example.js' {
  declare module.exports: $Exports<'mongodb-test-mock/example'>;
}
declare module 'mongodb-test-mock/index' {
  declare module.exports: $Exports<'mongodb-test-mock'>;
}
declare module 'mongodb-test-mock/index.js' {
  declare module.exports: $Exports<'mongodb-test-mock'>;
}
declare module 'mongodb-test-mock/MongoMock.js' {
  declare module.exports: $Exports<'mongodb-test-mock/MongoMock'>;
}
declare module 'mongodb-test-mock/test.js' {
  declare module.exports: $Exports<'mongodb-test-mock/test'>;
}
declare module 'mongodb-test-mock/test/collection.spec.js' {
  declare module.exports: $Exports<'mongodb-test-mock/test/collection.spec'>;
}
declare module 'mongodb-test-mock/test/common.js' {
  declare module.exports: $Exports<'mongodb-test-mock/test/common'>;
}
declare module 'mongodb-test-mock/test/jshint.spec.js' {
  declare module.exports: $Exports<'mongodb-test-mock/test/jshint.spec'>;
}
declare module 'mongodb-test-mock/test/MongoMock.spec.js' {
  declare module.exports: $Exports<'mongodb-test-mock/test/MongoMock.spec'>;
}
declare module 'mongodb-test-mock/test/util.spec.js' {
  declare module.exports: $Exports<'mongodb-test-mock/test/util.spec'>;
}
declare module 'mongodb-test-mock/util/index.js' {
  declare module.exports: $Exports<'mongodb-test-mock/util/index'>;
}
declare module 'mongodb-test-mock/util/objectUtil.js' {
  declare module.exports: $Exports<'mongodb-test-mock/util/objectUtil'>;
}
