// flow-typed signature: d67b8253f26ca8c3863f37725f4ef85b
// flow-typed version: <<STUB>>/nes_v^6.4.2/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'nes'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'nes' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'nes/client' {
  declare module.exports: any;
}

declare module 'nes/dist/client' {
  declare module.exports: any;
}

declare module 'nes/lib/client' {
  declare module.exports: any;
}

declare module 'nes/lib/index' {
  declare module.exports: any;
}

declare module 'nes/lib/listener' {
  declare module.exports: any;
}

declare module 'nes/lib/socket' {
  declare module.exports: any;
}

// Filename aliases
declare module 'nes/client.js' {
  declare module.exports: $Exports<'nes/client'>;
}
declare module 'nes/dist/client.js' {
  declare module.exports: $Exports<'nes/dist/client'>;
}
declare module 'nes/lib/client.js' {
  declare module.exports: $Exports<'nes/lib/client'>;
}
declare module 'nes/lib/index.js' {
  declare module.exports: $Exports<'nes/lib/index'>;
}
declare module 'nes/lib/listener.js' {
  declare module.exports: $Exports<'nes/lib/listener'>;
}
declare module 'nes/lib/socket.js' {
  declare module.exports: $Exports<'nes/lib/socket'>;
}
