// flow-typed signature: d7a7f7120c1ff76ece0a44fb5133300f
// flow-typed version: <<STUB>>/react-md-spinner_v^0.2.1/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-md-spinner'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-md-spinner' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-md-spinner/lib/index' {
  declare module.exports: any;
}

declare module 'react-md-spinner/lib/MDSpinner' {
  declare module.exports: any;
}

declare module 'react-md-spinner/lib/ssr-behavior' {
  declare module.exports: any;
}

declare module 'react-md-spinner/lib/styles' {
  declare module.exports: any;
}

declare module 'react-md-spinner/test/react-md-spinner.spec' {
  declare module.exports: any;
}

declare module 'react-md-spinner/test/ssr-behavior.spec' {
  declare module.exports: any;
}

declare module 'react-md-spinner/test/styles.spec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-md-spinner/lib/index.js' {
  declare module.exports: $Exports<'react-md-spinner/lib/index'>;
}
declare module 'react-md-spinner/lib/MDSpinner.js' {
  declare module.exports: $Exports<'react-md-spinner/lib/MDSpinner'>;
}
declare module 'react-md-spinner/lib/ssr-behavior.js' {
  declare module.exports: $Exports<'react-md-spinner/lib/ssr-behavior'>;
}
declare module 'react-md-spinner/lib/styles.js' {
  declare module.exports: $Exports<'react-md-spinner/lib/styles'>;
}
declare module 'react-md-spinner/test/react-md-spinner.spec.js' {
  declare module.exports: $Exports<'react-md-spinner/test/react-md-spinner.spec'>;
}
declare module 'react-md-spinner/test/ssr-behavior.spec.js' {
  declare module.exports: $Exports<'react-md-spinner/test/ssr-behavior.spec'>;
}
declare module 'react-md-spinner/test/styles.spec.js' {
  declare module.exports: $Exports<'react-md-spinner/test/styles.spec'>;
}
