// flow-typed signature: df6b732ff12c5266ad59d30421272e3a
// flow-typed version: <<STUB>>/react-boxen_v1.1.2/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-boxen'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-boxen' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-boxen/dist/web/index' {
  declare module.exports: any;
}

declare module 'react-boxen/web' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-boxen/dist/web/index.js' {
  declare module.exports: $Exports<'react-boxen/dist/web/index'>;
}
declare module 'react-boxen/web.js' {
  declare module.exports: $Exports<'react-boxen/web'>;
}
