// flow-typed signature: 4ef291db67955715268a0c86505c1f48
// flow-typed version: <<STUB>>/redux-factory_v^4.0.2/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-factory'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-factory' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-factory/src/compose' {
  declare module.exports: any;
}

declare module 'redux-factory/src/factory' {
  declare module.exports: any;
}

declare module 'redux-factory/src/helpers' {
  declare module.exports: any;
}

declare module 'redux-factory/src/reducerCreator' {
  declare module.exports: any;
}

declare module 'redux-factory/test/compose.test' {
  declare module.exports: any;
}

declare module 'redux-factory/test/factory.test' {
  declare module.exports: any;
}

declare module 'redux-factory/test/helpers.test' {
  declare module.exports: any;
}

declare module 'redux-factory/test/reducerCreator.test' {
  declare module.exports: any;
}

declare module 'redux-factory/test/testGlobals' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-factory/index' {
  declare module.exports: $Exports<'redux-factory'>;
}
declare module 'redux-factory/index.js' {
  declare module.exports: $Exports<'redux-factory'>;
}
declare module 'redux-factory/src/compose.js' {
  declare module.exports: $Exports<'redux-factory/src/compose'>;
}
declare module 'redux-factory/src/factory.js' {
  declare module.exports: $Exports<'redux-factory/src/factory'>;
}
declare module 'redux-factory/src/helpers.js' {
  declare module.exports: $Exports<'redux-factory/src/helpers'>;
}
declare module 'redux-factory/src/reducerCreator.js' {
  declare module.exports: $Exports<'redux-factory/src/reducerCreator'>;
}
declare module 'redux-factory/test/compose.test.js' {
  declare module.exports: $Exports<'redux-factory/test/compose.test'>;
}
declare module 'redux-factory/test/factory.test.js' {
  declare module.exports: $Exports<'redux-factory/test/factory.test'>;
}
declare module 'redux-factory/test/helpers.test.js' {
  declare module.exports: $Exports<'redux-factory/test/helpers.test'>;
}
declare module 'redux-factory/test/reducerCreator.test.js' {
  declare module.exports: $Exports<'redux-factory/test/reducerCreator.test'>;
}
declare module 'redux-factory/test/testGlobals.js' {
  declare module.exports: $Exports<'redux-factory/test/testGlobals'>;
}
