// flow-typed signature: 2bc28654c7c9bf58677e35c756e78ad5
// flow-typed version: <<STUB>>/svg-sprite-loader_v^0.3.0/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'svg-sprite-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'svg-sprite-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'svg-sprite-loader/config' {
  declare module.exports: any;
}

declare module 'svg-sprite-loader/lib/extract-svg-plugin' {
  declare module.exports: any;
}

declare module 'svg-sprite-loader/lib/processings/index' {
  declare module.exports: any;
}

declare module 'svg-sprite-loader/lib/processings/prefix-css-selectors' {
  declare module.exports: any;
}

declare module 'svg-sprite-loader/lib/processings/prefixize' {
  declare module.exports: any;
}

declare module 'svg-sprite-loader/lib/processings/raster-image-to-svg' {
  declare module.exports: any;
}

declare module 'svg-sprite-loader/lib/server-side-sprite' {
  declare module.exports: any;
}

declare module 'svg-sprite-loader/lib/svg-document' {
  declare module.exports: any;
}

declare module 'svg-sprite-loader/lib/utils' {
  declare module.exports: any;
}

declare module 'svg-sprite-loader/lib/web/angular-base-workaround' {
  declare module.exports: any;
}

declare module 'svg-sprite-loader/lib/web/global-sprite' {
  declare module.exports: any;
}

declare module 'svg-sprite-loader/lib/web/sprite' {
  declare module.exports: any;
}

// Filename aliases
declare module 'svg-sprite-loader/config.js' {
  declare module.exports: $Exports<'svg-sprite-loader/config'>;
}
declare module 'svg-sprite-loader/index' {
  declare module.exports: $Exports<'svg-sprite-loader'>;
}
declare module 'svg-sprite-loader/index.js' {
  declare module.exports: $Exports<'svg-sprite-loader'>;
}
declare module 'svg-sprite-loader/lib/extract-svg-plugin.js' {
  declare module.exports: $Exports<'svg-sprite-loader/lib/extract-svg-plugin'>;
}
declare module 'svg-sprite-loader/lib/processings/index.js' {
  declare module.exports: $Exports<'svg-sprite-loader/lib/processings/index'>;
}
declare module 'svg-sprite-loader/lib/processings/prefix-css-selectors.js' {
  declare module.exports: $Exports<'svg-sprite-loader/lib/processings/prefix-css-selectors'>;
}
declare module 'svg-sprite-loader/lib/processings/prefixize.js' {
  declare module.exports: $Exports<'svg-sprite-loader/lib/processings/prefixize'>;
}
declare module 'svg-sprite-loader/lib/processings/raster-image-to-svg.js' {
  declare module.exports: $Exports<'svg-sprite-loader/lib/processings/raster-image-to-svg'>;
}
declare module 'svg-sprite-loader/lib/server-side-sprite.js' {
  declare module.exports: $Exports<'svg-sprite-loader/lib/server-side-sprite'>;
}
declare module 'svg-sprite-loader/lib/svg-document.js' {
  declare module.exports: $Exports<'svg-sprite-loader/lib/svg-document'>;
}
declare module 'svg-sprite-loader/lib/utils.js' {
  declare module.exports: $Exports<'svg-sprite-loader/lib/utils'>;
}
declare module 'svg-sprite-loader/lib/web/angular-base-workaround.js' {
  declare module.exports: $Exports<'svg-sprite-loader/lib/web/angular-base-workaround'>;
}
declare module 'svg-sprite-loader/lib/web/global-sprite.js' {
  declare module.exports: $Exports<'svg-sprite-loader/lib/web/global-sprite'>;
}
declare module 'svg-sprite-loader/lib/web/sprite.js' {
  declare module.exports: $Exports<'svg-sprite-loader/lib/web/sprite'>;
}
