// flow-typed signature: 64a3e101d7097b13f30cd87b397c3d70
// flow-typed version: <<STUB>>/svg2png_v^4.1.1/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'svg2png'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'svg2png' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'svg2png/bin/svg2png-cli' {
  declare module.exports: any;
}

declare module 'svg2png/lib/converter' {
  declare module.exports: any;
}

declare module 'svg2png/lib/svg2png' {
  declare module.exports: any;
}

// Filename aliases
declare module 'svg2png/bin/svg2png-cli.js' {
  declare module.exports: $Exports<'svg2png/bin/svg2png-cli'>;
}
declare module 'svg2png/lib/converter.js' {
  declare module.exports: $Exports<'svg2png/lib/converter'>;
}
declare module 'svg2png/lib/svg2png.js' {
  declare module.exports: $Exports<'svg2png/lib/svg2png'>;
}
