module.exports = {
  DRAWING_COMPLETED: 'DRAWING_COMPLETED',
  DRAWING_STARTED: 'DRAWING_STARTED',
  DRAWING_CANCELLED: 'DRAWING_CANCELLED',
  CORPSE_CREATED: 'CORPSE_CREATED',
  CORPSE_COMPLETED: 'CORPSE_COMPLETED',
  DRAWING_EXPIRED: 'DRAWING_EXPIRED',
}
